import org.junit.Before;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;
import org.testng.AssertJUnit;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.By;

public class Queries {
    public static void main(String[] args) {
        System.out.println("Hello world!");
    }

    private static final TimeUnit GeneratedUtils = null;
    private static final String ExpectedConditions = null;
    public String baseUrl = "https://qnem103zatcwi.vodacom.corp:8443/";
    String driverPath = "C:\\chromedriver.exe";
    public static WebDriver driver;
    public String expected = null;
    public String actual;

    {
        actual = null;
    }

    @Before
    public void SiteTitle() {
        String expectedTitle = "Vodacom - Nemo";
        String actualTitle = driver.getTitle();
        AssertJUnit.assertEquals(actualTitle, expectedTitle);
    }

    @BeforeTest
    public void launchBrowser() throws InterruptedException {
        System.out.println("Launching Google chrome");
        System.setProperty("webdriver.chrome.driver", driverPath);
        driver = new ChromeDriver();
        driver.get(baseUrl);
        driver.manage().window().maximize();
    }

    @Test(priority = 0)
    public void WebQuery() throws InterruptedException {
        //Logging_On
        driver.findElement(By.id("username")).sendKeys("Nkanyiso111");
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".p-password-input")).sendKeys("Altron_2028");
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".p-button:nth-child(2)")).click();

        Thread.sleep(7000);
        driver.findElement(By.linkText("Queries")).click();
        Thread.sleep(5000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(5000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("New Case")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-card:nth-child(2) .inputSwitchMax:nth-child(2) .p-inputswitch-slider")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".mx-1\\.5")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".p-float-label:nth-child(2) .p-dropdown-trigger")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).sendKeys("Testing Web");
        Thread.sleep(3000);
        driver.findElement(By.name("newCommentBody")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("newCommentBody")).sendKeys("New Case");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".flex-wrap > .p-button")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("newCommentBody")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("newCommentBody")).sendKeys("Bad debt");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".inputSwitchDefault .p-inputswitch-slider")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".flex-wrap > .p-button")).click();
        Thread.sleep(3000);
        //driver.findElement(By.cssSelector(".p-card:nth-child(4) .inputSwitchMax:nth-child(2) .p-inputswitch-slider")).click();
        Thread.sleep(5000);
        driver.findElement(By.xpath("//*[@id=\"pr_id_41_header_1\"]/span[1]")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".h-8 > .p-dropdown-trigger:nth-child(4) > .p-dropdown-trigger-icon")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(5000);
        driver.findElement(By.name("webDetails.searchNumbersList")).click();
        Thread.sleep(5000);
        driver.findElement(By.name("webDetails.searchNumbersList")).click();
        Thread.sleep(5000);
        driver.findElement(By.name("webDetails.searchNumbersList")).sendKeys("27712084689");
        driver.findElement(By.name("webDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".p-float-label:nth-child(2) .p-button")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".p-dropdown:nth-child(2) .p-dropdown-trigger-icon")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".p-1:nth-child(1) .p-dropdown-trigger-icon")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(2)")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(3) > span")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".justify-between > .p-button:nth-child(6)")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".pi-chevron-left")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".text-right:nth-child(1)")).click();
        Thread.sleep(5000);
        driver.findElement(By.id("pr_id_56_header_1")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".bg-nemoGray-l")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(7000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(7000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector("#pr_id_54_content_0 .p-button:nth-child(4)")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".p-menuitem:nth-child(2) .p-menuitem-text:nth-child(2)")).click();
        Thread.sleep(5000);
        driver.findElement(By.id("pr_id_56_header_0")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".p-1")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".p-menuitem:nth-child(7) .p-menuitem-text:nth-child(2)")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".p-confirm-dialog-accept")).click();
    }
    @Test(priority = 1)
    public void Pin_Puk_Query() throws InterruptedException {
        //Logging_On
        driver.findElement(By.id("username")).sendKeys("Nkanyiso111");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-password-input")).sendKeys("Altron_2028");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-button:nth-child(2)")).click();
        Thread.sleep(5000);

        //Case creation
        Thread.sleep(5000);
        driver.findElement(By.linkText("Queries")).click();
        Thread.sleep(4000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(4000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(4000);
        driver.findElement(By.linkText("New Case")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-card:nth-child(2) .inputSwitchMax:nth-child(3) .p-inputswitch-slider")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".mx-1\\.5")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-float-label:nth-child(2) .p-dropdown-trigger")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(2)")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).sendKeys("Testing Pin Puk");
        Thread.sleep(4000);
        driver.findElement(By.name("newCommentBody")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("newCommentBody")).sendKeys("Pin Puk Query");
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".inputSwitchDefault .p-inputswitch-slider")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".flex-wrap > .p-button")).click();
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_41_header_1")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".invalidField > .p-dropdown")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("pinPukDetails.searchNumbersList")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("pinPukDetails.searchNumbersList")).sendKeys("27823330513");
        driver.findElement(By.name("pinPukDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(4000);
        driver.findElement(By.name("pinPukDetails.searchNumbersList")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("pinPukDetails.searchNumbersList")).sendKeys("27723888468");
        driver.findElement(By.name("pinPukDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(4000);
        driver.findElement(By.name("pinPukDetails.searchNumbersList")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("pinPukDetails.searchNumbersList")).sendKeys("27662203330");
        driver.findElement(By.name("pinPukDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".pi-chevron-left")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".text-right:nth-child(1)")).click();
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_56_header_1")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".bg-nemoGray-l")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(6000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(6000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".bg-nemoGray-l")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-1")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-menuitem:nth-child(7) .p-menuitem-text:nth-child(2)")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-confirm-dialog-accept")).click();
    }
    @Test(priority = 2)
    public void Sim_Swap_Query() throws InterruptedException {
        //Logging_On
        driver.findElement(By.id("username")).sendKeys("Nkanyiso111");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-password-input")).sendKeys("Altron_2028");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-button:nth-child(2)")).click();

        Thread.sleep(5000);
        driver.findElement(By.linkText("Queries")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("New Case")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-card:nth-child(2) .inputSwitchMax:nth-child(4) .p-inputswitch-slider")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".mx-1\\.5")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".invalidField .p-dropdown-trigger-icon")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).sendKeys("Account Paid Sim Swap required");
        Thread.sleep(3000);
        driver.findElement(By.name("newCommentBody")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("newCommentBody")).sendKeys("Sim Swap ");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".flex-wrap > .p-button")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("newCommentBody")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("newCommentBody")).sendKeys("Paid");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".inputSwitchDefault .p-inputswitch-slider")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".flex-wrap > .p-button")).click();
        Thread.sleep(3000);
        driver.findElement(By.xpath("//*[@id=\"pr_id_41_header_1\"]/span[1]")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("simSwapDetails.searchNumbersList")).click();
        driver.findElement(By.name("simSwapDetails.searchNumbersList")).click();
        Thread.sleep(5000);
        driver.findElement(By.name("simSwapDetails.searchNumbersList")).sendKeys("27829028575");
        driver.findElement(By.name("simSwapDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(5000);
        driver.findElement(By.name("simSwapDetails.searchNumbersList")).click();
        Thread.sleep(5000);
        driver.findElement(By.name("simSwapDetails.searchNumbersList")).sendKeys("27833765656");
        driver.findElement(By.name("simSwapDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(5000);
        driver.findElement(By.name("simSwapDetails.searchNumbersList")).click();
        Thread.sleep(5000);
        driver.findElement(By.name("simSwapDetails.searchNumbersList")).sendKeys("27662203330");
        driver.findElement(By.name("simSwapDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".bg-nemoGray-l")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".text-right:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_53_header_1")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".bg-nemoGray-l")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_53_header_0")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-1")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("LOGOFF")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-confirm-dialog-accept")).click();
    }
    @Test(priority = 3)
    public void InternalQuery() throws InterruptedException {
        //Logging_On
        driver.findElement(By.id("username")).sendKeys("Nkanyiso111");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-password-input")).sendKeys("Altron_2028");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-button:nth-child(2)")).click();

        Thread.sleep(4000);
        driver.findElement(By.linkText("Queries")).click();
        Thread.sleep(4000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(4000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(4000);
        driver.findElement(By.linkText("New Case")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-card:nth-child(2) .inputSwitchMax:nth-child(6) .p-inputswitch-slider")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".mx-1\\.5")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-float-label:nth-child(2) .p-dropdown-trigger-icon")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(2)")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).sendKeys("Internal query for User");
        Thread.sleep(4000);
        driver.findElement(By.name("newCommentBody")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("newCommentBody")).sendKeys("Bad debt query");
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".inputSwitchDefault .p-inputswitch-slider")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".flex-wrap > .p-button")).click();
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_41_header_1")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".h-8 > .p-dropdown-trigger:nth-child(4)")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-chips-multiple-container")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("internalDetails.searchNumbersList")).sendKeys("27712084689");
        driver.findElement(By.name("internalDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(4000);
        driver.findElement(By.name("internalDetails.searchNumbersList")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("internalDetails.searchNumbersList")).sendKeys("27723888468");
        driver.findElement(By.name("internalDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(4000);
        driver.findElement(By.name("internalDetails.searchNumbersList")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("internalDetails.searchNumbersList")).sendKeys("27824401297");
        driver.findElement(By.name("internalDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".w-56:nth-child(4) .p-inputswitch-slider")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".w-56:nth-child(5) .p-inputswitch-slider")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("internalDetails.searchNumbersList")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("internalDetails.searchNumbersList")).sendKeys("27662203330");
        Thread.sleep(4000);
        driver.findElement(By.name("internalDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".w-56:nth-child(7) .p-inputswitch-slider")).click();
        Thread.sleep(6000);
        driver.findElement(By.cssSelector(".w-56:nth-child(8) .p-inputswitch-slider")).click();
        Thread.sleep(6000);
        driver.findElement(By.cssSelector(".w-56:nth-child(9) .p-inputswitch-slider")).click();
        Thread.sleep(6000);
        driver.findElement(By.cssSelector(".w-56:nth-child(10) .p-inputswitch-slider")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-float-label:nth-child(1) .p-button")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-dropdown:nth-child(2) .p-dropdown-trigger-icon")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(3)")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-1:nth-child(1) .p-dropdown-trigger-icon")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(6)")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector("tr:nth-child(5) > td:nth-child(1) > span")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".justify-between > .p-button:nth-child(6)")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".pi-chevron-left")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".text-right:nth-child(1)")).click();
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_56_header_1")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".pi-chevron-left")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_54_header_4")).click();
        Thread.sleep(6000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(6000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(6000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(6000);
        driver.findElement(By.cssSelector("#pr_id_54_content_4 .p-button:nth-child(4)")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-menuitem:nth-child(2) .p-menuitem-text:nth-child(2)")).click();
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_56_header_0")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-1")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-menuitem:nth-child(7) .p-menuitem-text:nth-child(2)")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-confirm-dialog-accept")).click();
    }
    @Test(priority = 4)
    public void PamsQuery() throws InterruptedException {
        //Logging_On
        driver.findElement(By.id("username")).sendKeys("Nkanyiso111");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-password-input")).sendKeys("Altron_2028");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-button:nth-child(2)")).click();

        Thread.sleep(4000);
        driver.findElement(By.linkText("Queries")).click();
        Thread.sleep(4000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(4000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(4000);
        driver.findElement(By.linkText("New Case")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".inputSwitchMax:nth-child(8) .p-inputswitch-slider")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-card:nth-child(4) .inputSwitchMax:nth-child(2) .p-inputswitch-slider")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-card:nth-child(4) .inputSwitchMax:nth-child(3) .p-inputswitch-slider")).click();
        Thread.sleep(4000);

        driver.findElement(By.cssSelector(".p-card:nth-child(4) .inputSwitchMax:nth-child(4) .p-inputswitch-slider")).click();

        driver.findElement(By.cssSelector(".flex > .mx-1\\.5")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".flex:nth-child(1) > .p-float-label:nth-child(2) .p-dropdown-trigger:nth-child(5) > .p-dropdown-trigger-icon")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).sendKeys("Pams Testing");
        Thread.sleep(4000);
        driver.findElement(By.name("newCommentBody")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("newCommentBody")).sendKeys("Account Paid ");
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".flex-wrap > .p-button")).click();
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_41_header_1")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("pamsDetails.msisdnNumbers")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("pamsDetails.msisdnNumbers")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("pamsDetails.msisdnNumbers")).sendKeys("27829808335");
        driver.findElement(By.name("pamsDetails.msisdnNumbers")).sendKeys(Keys.ENTER);
        Thread.sleep(4000);
        driver.findElement(By.name("pamsDetails.cardNumbers")).click();
        driver.findElement(By.name("pamsDetails.cardNumbers")).sendKeys("16797549644");
        driver.findElement(By.name("pamsDetails.cardNumbers")).sendKeys(Keys.ENTER);
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".flex:nth-child(2) .p-chips > .p-inputtext")).click();
        driver.findElement(By.name("pamsDetails.batchNumbers")).sendKeys("52980453");
        driver.findElement(By.name("pamsDetails.batchNumbers")).sendKeys(Keys.ENTER);
        Thread.sleep(4000);
        driver.findElement(By.name("pamsDetails.voucherNumbers")).click();
        driver.findElement(By.name("pamsDetails.voucherNumbers")).sendKeys("140531229313");
        driver.findElement(By.name("pamsDetails.voucherNumbers")).sendKeys(Keys.ENTER);
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_41_header_2")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".flex > .p-card .p-float-label:nth-child(1) .p-dropdown-trigger-icon")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("memoDetails.invOfficer")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-float-label:nth-child(3) .p-dropdown-trigger")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_41_header_3")).click();
        Thread.sleep(4000);

        driver.findElement(By.cssSelector(".flex:nth-child(1) > .p-float-label:nth-child(1) .p-dropdown-trigger:nth-child(4) > .p-dropdown-trigger-icon")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".invalidField:nth-child(1) .p-dropdown-trigger")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("statementDetails.invOfficer")).click();
        Thread.sleep(4000);
        driver.findElement(By.name("statementDetails.invOfficer")).sendKeys("Mr Ngobese");
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".w-96 .p-dropdown-trigger-icon")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(2)")).click();
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_41_header_4")).click();
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_41_header_1")).click();
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_41_header_0")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".pi-chevron-left")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".text-right:nth-child(1)")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".bg-nemoGray-l")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_62_header_1")).click();
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_57_header_1")).click();
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_57_header_2")).click();
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_57_header_3")).click();
        Thread.sleep(4000);
        driver.findElement(By.id("pr_id_62_header_0")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-1")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-menuitem:nth-child(7) .p-menuitem-text:nth-child(2)")).click();
        Thread.sleep(4000);
        driver.findElement(By.cssSelector(".p-confirm-dialog-accept")).click();
    }
    @Test(priority = 5)
    public void SubscriberProfileQuery() throws InterruptedException {
        //Logging_On
        driver.findElement(By.id("username")).sendKeys("Nkanyiso111");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-password-input")).sendKeys("Altron_2028");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-button:nth-child(2)")).click();

        Thread.sleep(5000);
        driver.findElement(By.linkText("Queries")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("New Case")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".inputSwitchMax:nth-child(7) .p-inputswitch-slider")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".mx-1\\.5")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-float-label:nth-child(2) .p-dropdown-trigger-icon")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).sendKeys("Sub Profile Testing");
        Thread.sleep(3000);
        driver.findElement(By.name("newCommentBody")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("newCommentBody")).sendKeys("Testing");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".flex-wrap > .p-button")).click();
        Thread.sleep(3000);
        driver.findElement(By.xpath("//*[@id=\"pr_id_41_header_1\"]/span[1]")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".h-8 > .p-dropdown-trigger:nth-child(4) > .p-dropdown-trigger-icon")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("subscriberProfileDetails.searchNumbersList")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("subscriberProfileDetails.searchNumbersList")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("subscriberProfileDetails.searchNumbersList")).sendKeys("27833765656");
        Thread.sleep(3000);
        driver.findElement(By.name("subscriberProfileDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".bg-nemoGray-l")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".text-right:nth-child(1)")).click();
        Thread.sleep(3000);

        driver.findElement(By.cssSelector(".p-1")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-menuitem:nth-child(7) .p-menuitem-text:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-confirm-dialog-accept")).click();
    }
    @Test(priority = 6)
    public void SubscriberRegQuery() throws InterruptedException {
        //Logging_On
        driver.findElement(By.id("username")).sendKeys("Nkanyiso111");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-password-input")).sendKeys("Altron_2028");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-button:nth-child(2)")).click();

        Thread.sleep(5000);
        driver.findElement(By.linkText("Queries")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("New Case")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-card:nth-child(2) .inputSwitchMax:nth-child(5) .p-inputswitch-slider")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".mx-1\\.5")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".invalidField .p-dropdown-trigger")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(4)")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).sendKeys("Sub Reg Testing");
        Thread.sleep(3000);
        driver.findElement(By.name("newCommentBody")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("newCommentBody")).sendKeys("Email Interception Case");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".flex-wrap > .p-button")).click();
        Thread.sleep(3000);
        driver.findElement(By.xpath("//*[@id=\"pr_id_41_header_1\"]/span[1]")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("subscriberRegistrationDetails.msisdnNumbers")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("subscriberRegistrationDetails.msisdnNumbers")).sendKeys("27737334945");
        Thread.sleep(3000);
        driver.findElement(By.name("subscriberRegistrationDetails.msisdnNumbers")).sendKeys(Keys.ENTER);
        Thread.sleep(3000);
        driver.findElement(By.name("subscriberRegistrationDetails.imsiNumbers")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("subscriberRegistrationDetails.imsiNumbers")).sendKeys("655015200778738");
        Thread.sleep(3000);
        driver.findElement(By.name("subscriberRegistrationDetails.imsiNumbers")).sendKeys(Keys.ENTER);
        Thread.sleep(3000);
        driver.findElement(By.name("subscriberRegistrationDetails.iccidNumbers")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("subscriberRegistrationDetails.iccidNumbers")).sendKeys("89555000000003607402");
        Thread.sleep(3000);
        driver.findElement(By.name("subscriberRegistrationDetails.iccidNumbers")).sendKeys(Keys.ENTER);
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".pi-chevron-left")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".text-right:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_53_header_1")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".bg-nemoGray-l")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(7000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(7000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_53_header_0")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-1")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("LOGOFF")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-confirm-dialog-accept")).click();
    }
    @Test(priority = 7)
    public void CallDataQuery() throws InterruptedException {
        //Logging_On
        driver.findElement(By.id("username")).sendKeys("Nkanyiso111");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-password-input")).sendKeys("Altron_2028");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-button:nth-child(2)")).click();


        Thread.sleep(5000);
        driver.findElement(By.linkText("Queries")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("New Case")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".inputSwitchMax:nth-child(10) .p-inputswitch-slider")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".mx-1\\.5")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-float-label:nth-child(2) .p-dropdown-trigger-icon")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).sendKeys("Call Data Test");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-card:nth-child(4) .inputSwitchMax:nth-child(2) .p-inputswitch-slider")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("newCommentBody")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("newCommentBody")).sendKeys("Account Paid ");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".inputSwitchDefault .p-inputswitch-slider")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".flex-wrap > .p-button")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_41_header_1")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-float-label:nth-child(1) .p-dropdown-trigger:nth-child(4)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("callDataDetails.searchNumbersList")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("callDataDetails.searchNumbersList")).sendKeys("27673199721");
        Thread.sleep(3000);
        driver.findElement(By.name("callDataDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(3000);
        driver.findElement(By.name("callDataDetails.searchNumbersList")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("callDataDetails.searchNumbersList")).sendKeys("27824401297");
        driver.findElement(By.name("callDataDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(3000);
        driver.findElement(By.name("callDataDetails.searchNumbersList")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("callDataDetails.searchNumbersList")).sendKeys("27104954930");
        driver.findElement(By.name("callDataDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(3000);
        driver.findElement(By.name("callDataDetails.searchNumbersList")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("callDataDetails.searchNumbersList")).sendKeys("27662203330");
        driver.findElement(By.name("callDataDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".w-56:nth-child(5) .p-inputswitch-slider")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("callDataDetails.searchNumbersList")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("callDataDetails.searchNumbersList")).sendKeys("27824551389");
        Thread.sleep(3000);
        driver.findElement(By.name("callDataDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".w-56:nth-child(7) .p-inputswitch-slider")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".w-56:nth-child(8) .p-inputswitch-slider")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".w-56:nth-child(10) .p-inputswitch-slider")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-float-label:nth-child(1) .p-button")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown:nth-child(2) .p-dropdown-trigger-icon")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(3)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-datepicker-title > .p-dropdown:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(4)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2) > span")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".justify-between > .p-button:nth-child(6)")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_41_header_2")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".invalidField .p-inputswitch-slider")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".invalidField:nth-child(1) .p-dropdown-trigger-icon")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("memoDetails.invOfficer")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".h-8 > .p-dropdown-trigger:nth-child(4) > .p-dropdown-trigger-icon")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".pi-chevron-left")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".text-right:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".pi-chevron-left")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_58_header_1")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_55_header_1")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_55_header_2")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_55_header_3")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_55_header_4")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_55_header_5")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_55_header_6")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector("#pr_id_55_content_6 .p-button:nth-child(4) > .p-button-icon")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("Export to XLS")).click();
        driver.findElement(By.cssSelector(".p-1")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("LOGOFF")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-confirm-dialog-accept")).click();
      

    }
    @Test(priority = 8)
    public void HandsetQuery() throws InterruptedException {

        //Logging_On
        driver.findElement(By.id("username")).sendKeys("Nkanyiso111");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-password-input")).sendKeys("Altron_2028");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-button:nth-child(2)")).click();

        Thread.sleep(5000);
        driver.findElement(By.linkText("Queries")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("New Case")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".inputSwitchMax:nth-child(9) .p-inputswitch-slider")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".mx-1\\.5")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".invalidField .p-dropdown-trigger-icon")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).sendKeys("Handset Usage query");
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_41_header_1")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("handsetUsageDetails.msisdnNumbers")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("handsetUsageDetails.msisdnNumbers")).sendKeys("27714579819");
        Thread.sleep(3000);
        driver.findElement(By.name("handsetUsageDetails.msisdnNumbers")).sendKeys(Keys.ENTER);
        Thread.sleep(3000);
        driver.findElement(By.name("handsetUsageDetails.imsiNumbers")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("handsetUsageDetails.imsiNumbers")).sendKeys("655016040434849");
        driver.findElement(By.name("handsetUsageDetails.imsiNumbers")).sendKeys(Keys.ENTER);
        Thread.sleep(3000);
        driver.findElement(By.name("handsetUsageDetails.imeiNumbers")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("handsetUsageDetails.imeiNumbers")).sendKeys("350272251666500");
        driver.findElement(By.name("handsetUsageDetails.imeiNumbers")).sendKeys(Keys.ENTER);
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".pi-chevron-left")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".text-right:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_56_header_1")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_54_header_2")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_54_header_1")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_54_header_0")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".bg-nemoGray-l")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector("#pr_id_54_content_0 .p-button:nth-child(4)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".pi-file-excel")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_56_header_0")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-1")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-menuitem:nth-child(7) .p-menuitem-text:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-confirm-dialog-accept")).click();
    }
    @Test(priority = 9)
    public void PoliceQuery() throws InterruptedException {
        //Logging_On
        driver.findElement(By.id("username")).sendKeys("Nkanyiso111");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-password-input")).sendKeys("Altron_2028");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-button:nth-child(2)")).click();

        Thread.sleep(5000);
        driver.findElement(By.linkText("Queries")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("New Case")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-card:nth-child(2) .inputSwitchMax:nth-child(1) .p-inputswitch-slider")).click();
        driver.findElement(By.cssSelector(".mx-1\\.5")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-float-label:nth-child(2) .p-dropdown-trigger-icon")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.investigatingOfficer")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.investigatingOfficer")).sendKeys("Mr Ngobese");
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.caseNumber")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.caseNumber")).sendKeys("123665");
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.referenceNumber")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.referenceNumber")).sendKeys("5625");
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.caseDescription")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.caseDescription")).sendKeys("Police Case Query");
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_41_header_1")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".h-8 > .p-dropdown-trigger:nth-child(4)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("policeCaseDetails.searchNumbersList")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("policeCaseDetails.searchNumbersList")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("policeCaseDetails.searchNumbersList")).sendKeys("27823330513");
        driver.findElement(By.name("policeCaseDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(3000);
        driver.findElement(By.name("policeCaseDetails.searchNumbersList")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("policeCaseDetails.searchNumbersList")).sendKeys("27818082342");
        driver.findElement(By.name("policeCaseDetails.searchNumbersList")).sendKeys(Keys.ENTER);
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-float-label:nth-child(1) .p-button")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-1:nth-child(1) > .p-dropdown-trigger")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(4)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(2) > span")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".justify-between > .p-button:nth-child(6)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-float-label:nth-child(1) .p-button")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(3)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".justify-between > .p-button:nth-child(6)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".pi-chevron-left")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".text-right:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_56_header_1")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".pi-chevron-left")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_54_header_1")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-radiobutton:nth-child(4) > .p-radiobutton-box")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_54_header_2")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_54_header_3")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_54_header_4")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_54_header_5")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_54_header_6")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_54_header_10")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector("#pr_id_54_content_10 .p-button:nth-child(4)")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("Export to XLS")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_56_header_0")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-1")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-menuitem:nth-child(7) .p-menuitem-text:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-confirm-dialog-accept")).click();
    }
    @Test(priority = 10)
    public void OnwershipQuery() throws InterruptedException {
        //Logging_On
        driver.findElement(By.id("username")).sendKeys("Nkanyiso111");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-password-input")).sendKeys("Altron_2028");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-button:nth-child(2)")).click();

        Thread.sleep(5000);
        driver.findElement(By.linkText("Queries")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("Cases")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("New Case")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".inputSwitchMax:nth-child(11) .p-inputswitch-slider")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".mx-1\\.5")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".invalidField .p-dropdown-trigger-icon")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("caseCriteria.auditReasonText")).sendKeys("Ownership Details query");
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_41_header_1")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-float-label:nth-child(1) .p-dropdown-trigger:nth-child(4) > .p-dropdown-trigger-icon")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("ownershipDetailsDetails.subscriberID")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("ownershipDetailsDetails.subscriberID")).sendKeys("27833765656");
        Thread.sleep(3000);
        driver.findElement(By.name("ownershipDetailsDetails.subscriberID")).sendKeys(Keys.ENTER);
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".h-8 > .p-dropdown-trigger:nth-child(4)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".flex-wrap:nth-child(1) > .p-button")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-float-label:nth-child(1) .p-dropdown-trigger:nth-child(4) > .p-dropdown-trigger-icon")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("ownershipDetailsDetails.subscriberID")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("ownershipDetailsDetails.subscriberID")).sendKeys("89484600000007914843");
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".h-8 > .p-dropdown-trigger:nth-child(4) > .p-dropdown-trigger-icon")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".flex-wrap:nth-child(1) > .p-button")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-float-label:nth-child(1) .p-dropdown-trigger:nth-child(4) > .p-dropdown-trigger-icon")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-dropdown-item:nth-child(3)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-card-content:nth-child(2) .p-dropdown-clear-icon")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".bg-nemoGray-l")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".text-right:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_55_header_1")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".bg-nemoGray-l")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".whitespace-nowrap:nth-child(2)")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".flex > .flex > .displayTextOnly:nth-child(1)")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("pr_id_55_header_0")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-1")).click();
        Thread.sleep(3000);
        driver.findElement(By.linkText("LOGOFF")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".p-confirm-dialog-accept")).click();
    }
    @AfterClass
    static void tearDown() {
        if (driver != null) {
            driver.quit();
        }

    }
}
